### ISSUE TITLE
IceWM doesn't display any Chinese/Japanese/Korean texts

### ISSUE THREAD

**Issue by guoyunhe** [openSUSE/icewm-config-openSUSE#2]
It seems the icewm preferences do not use a proper font family for CJK texts. In CJK systems, the whole desktop can only render a few English texts but all CJK texts are missing.

Tested on openSUSE Leap 42.1 and Tumbleweed 20170123.

**Comment by yifanjiang** [comment]
should be fixed with https://github.com/openSUSE/icewm-config-openSUSE/pull/6
