### ISSUE TITLE
MenuMouseTracking should be enabled by default

### ISSUE THREAD

**Issue by micrococo** [openSUSE/icewm-config-openSUSE#3]
Hi.

The behavior provided by `MenuMouseTracking` is the default on almost every desktop and window manager. Please, enable it by default.

Greetings.

**Comment by yifanjiang** [comment]
Thanks for the nice idea!

https://github.com/openSUSE/icewm-config-openSUSE/commit/0f55aadcbdab06ac97bf48b8f2587d9697b6f732
