### ISSUE TITLE
 Chinese characters can't be shown correctly in IceWM session menu.

### ISSUE THREAD

**Issue by zhengqiang130** [openSUSE/icewm-config-openSUSE#5]
Language: Simplified Chinese

Steps:
1. Install SLED15 with Simplified Chinese language.
2. Login the system with IceWM Session
3. Launch xterm and execute ls

Actual Results:
Some of the folders' name shown as junk character.
Please find the attachment for details.

**Comment by yifanjiang** [comment]
should be fixed with https://github.com/openSUSE/icewm-config-openSUSE/pull/6
